return {
  theme = "doom",
  config = {
    header = {
      [[]],
      [[]],
      [[]],
      [[]],
      [[]],
      [[]],
      [[]],
      [[]],
      [[███╗   ██╗███████╗ ██████╗ ██╗   ██╗██╗███╗   ███╗]],
      [[████╗  ██║██╔════╝██╔═══██╗██║   ██║██║████╗ ████║]],
      [[██╔██╗ ██║█████╗  ██║   ██║██║   ██║██║██╔████╔██║]],
      [[██║╚██╗██║██╔══╝  ██║   ██║╚██╗ ██╔╝██║██║╚██╔╝██║]],
      [[██║ ╚████║███████╗╚██████╔╝ ╚████╔╝ ██║██║ ╚═╝ ██║]],
      [[╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝     ╚═╝]],
      [[]],
      [[]],
    },
    center = {
      {
        icon = "  ",
        icon_hl = "Title",
        desc = "Projects                                ",
        desc_hl = "String",
        key = "p",
        key_hl = "Number",
        action = "Telescope projects",
      },
      {
        icon = "  ",
        icon_hl = "Title",
        desc = "Recently Files                          ",
        desc_hl = "String",
        key = "o",
        key_hl = "Number",
        action = "Telescope oldfiles",
      },
      {
        icon = "󰥨  ",
        icon_hl = "Title",
        desc = "Find Files                              ",
        desc_hl = "String",
        key = "f",
        key_hl = "Number",
        action = "Telescope find_files",
      },
      {
        icon = "󰒲  ",
        icon_hl = "Title",
        desc = "Lazy                                    ",
        desc_hl = "String",
        key = "l",
        key_hl = "Number",
        action = "Lazy",
      },
      {
        icon = "  ",
        icon_hl = "Title",
        desc = "Config                                  ",
        desc_hl = "String",
        key = "c",
        key_hl = "Number",
        action = "edit ~/.config/nvim/lua/core/lazy.lua",
      },
      {
        icon = "  ",
        icon_hl = "Title",
        desc = "Quit                                    ",
        desc_hl = "String",
        key = "q",
        key_hl = "Number",
        action = "qa",
      },
    },
    footer = function()
      local stats = require("lazy").stats()
      local ms = (math.floor(stats.startuptime * 100 + 0.5) / 100)
      return {
        "",
        "Talk is cheap. Show me the code.",
        "",
        "⚡ Neovim loaded " .. stats.loaded .. "/" .. stats.count .. " plugins in " .. ms .. "ms",
      }
    end,
  },
}
