return {
  ensure_installed = {
    "bash",
    "c",
    "cpp",
    "c_sharp",
    "cmake",
    "html",
    "javascript",
    "jsdoc",
    "json",
    "jsonc",
    "css",
    "lua",
    "luadoc",
    "luap",
    "markdown",
    "markdown_inline",
    "python",
    "query",
    "regex",
    "tsx",
    "typescript",
    "vim",
    "vimdoc",
    "yaml",
    "dockerfile",
    "fish",
    "go",
    "gomod",
    "gosum",
    "sql",
    "rust",
    "ninja",
    "rst",
    "toml",
    "ron",
  },
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "<CR>",
      node_incremental = "<CR>",
      node_decremental = "<BS>",
      scope_incremental = "<TAB>",
    },
  },
}
