return {
  "stevearc/conform.nvim",
  dependencies = { "mason.nvim" },
  lazy = true,
  cmd = "ConformInfo",
  -- stylua: ignore
  keys = { { mode = { "n" }, "<leader>lf", function() require("conform").format() end, desc = "Format" } },
  opts = {
    formatters_by_ft = {
      lua = { "stylua" },
      nix = { "nixfmt" },
      c = { "clang_format" },
      cpp = { "clang_format" },
      cmake = { "cmake_format" },
      go = { "gofumpt" },
      sh = { "shfmt" },
      json = { "jq" },
      jsonc = { "prettier" },
      sql = { "sql_formatter" },
      zsh = { "beautysh" },
      javascript = { "prettier" },
      javascriptreact = { "prettier" },
      typescript = { "prettier" },
      typescriptreact = { "prettier" },
      vue = { "prettier" },
      css = { "prettier" },
      scss = { "prettier" },
      less = { "prettier" },
      html = { "prettier" },
      yaml = { "prettier" },
      markdown = { "prettier" },
      graphql = { "prettier" },
      handlebars = { "prettier" },
    },
  },
}
